name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
      env:
        MAKEFLAGS: "-j2"
    - name: ls
      run: cd build && ls -l
    - name: test
      run: cd build && ctest -j2
    - name: ls
      run: cd build && ls -l
    - name: Upload zip
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-build
        path: build/test

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release
      env:
        MAKEFLAGS: "-j2"
    - name: ls
      run: cd build && dir
    - name: test
      run: cd build && ctest -j2 
    - name: ls
      run: cd build && dir
    - name: Upload zip
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: build/Release/test.exe
